"""empty message

Revision ID: a1a7c405f033
Revises: 7ce58c961c95
Create Date: 2024-01-31 16:51:14.091397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a7c405f033'
down_revision = '7ce58c961c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('biography')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biography', sa.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
