"""empty message

Revision ID: 7ce58c961c95
Revises: 8f3bcb20c8bb
Create Date: 2024-01-31 16:34:18.421744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce58c961c95'
down_revision = '8f3bcb20c8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('biography',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('biography',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
