"""empty message

Revision ID: 344eaba7d582
Revises: 4d26f99b379f
Create Date: 2024-04-22 11:18:33.453008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344eaba7d582'
down_revision = '4d26f99b379f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
