"""empty message

Revision ID: 6902c95ea07e
Revises: 4a23100d4c56
Create Date: 2024-02-02 11:12:04.877709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6902c95ea07e'
down_revision = '4a23100d4c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authored_poems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authored_poems',
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('poem_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['poem_id'], ['poems.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'poem_id')
    )
    # ### end Alembic commands ###
